clc;
clear;
clf;
close;
x=[1,2,1,1];
xn=[0:3];
h=[1,1,1,1];
hn=[0:3];
y=conv(x,h);
yn=[min(xn)+min(hn):max(xn)+max(hn)];
subplot(3,1,1);
plot2d3(xn,x,-3);
mtlb_axis([-1 5 0 3]);
xlabel('n');
ylabel('value');
title('x(n)');
xgrid();
subplot(3,1,2);
plot2d3(hn,h,-3);
mtlb_axis([-1 5 0 3]);
xlabel('n');
ylabel('value');
title('h(n)');
xgrid();
subplot(3,1,3);
plot2d3(yn,y,-3);
mtlb_axis([-1 7 0 6]);
xlabel('n');
ylabel('value');
title('y(n)');
xgrid();